### ISSUE TITLE
package NewsParser to PyPI

### ISSUE THREAD

**Issue by bustta** [Lab-317/NewsParser#14]

**Comment by bustta** [comment]
@BalicantaYao https://pypi.python.org/pypi/NewsParser/0.0.1 works?

**Comment by BalicantaYao** [comment]
@bustta  一定要這麼強嗎？

**Comment by BalicantaYao** [comment]
@bustta 可是我裝的時候報錯了!

**Comment by bustta** [comment]
有錯正常，對了我才驚訝XD 還要再去看文件

**Comment by bustta** [comment]
108 downloads in the last day
這人數是認真的嗎？又還不能用，會不會來這裡幹爆我們...

**Comment by BalicantaYao** [comment]
我也覺得怪，不會吧，這個應該是假的

**Comment by bustta** [comment]
https://pypi.python.org/pypi/newsParser/0.0.4

> pip install newsParser
