### ISSUE TITLE
[Decode error - output not utf-8] under Windows ST3

### ISSUE THREAD

**Issue by bustta** [Lab-317/NewsParser#2]
windows 下用ST3 build會死

**Comment by BalicantaYao** [comment]
你在 Mac 底下不會嗎？

**Comment by bustta** [comment]
mac不會。
windows用cmd跑也不會，所以windows就用cmd跑，deal !

你是不是得了中英間一定要空格的強迫症?!

**Comment by BalicantaYao** [comment]
@bustta  身為一個知識份子，這是對排版的一種尊重，難到你不覺得，分了比較好看嗎？
