### ISSUE TITLE
檔案結構看起來不爽

### ISSUE THREAD

**Issue by bustta** [Lab-317/NewsParser#23]
from newsParser.NewsParser import NewsParser
要這樣才能用

**Comment by BalicantaYao** [comment]
@bustta  你是說用 pip 安裝以後嗎？

**Comment by bustta** [comment]
@BalicantaYao 對

**Comment by BalicantaYao** [comment]
`from newsParser import NewsParser`

這樣應該行，看要改哪個資料夾

**Comment by bustta** [comment]
應該是要這樣啊，不過現在這樣會報錯

**Comment by BalicantaYao** [comment]
不會吧，我的是正常的啊

**Comment by bustta** [comment]
我如果只有
`from newsParser import NewsParser`
他會說module object not callable耶，怪了

**Comment by BalicantaYao** [comment]
不會怪，這蠻有可能的

**Comment by bustta** [comment]
...那看怎麼搬才能避免這情形

**Comment by BalicantaYao** [comment]
http://stackoverflow.com/a/45126/3413444

**Comment by bustta** [comment]
good, fix it please.

2014-11-05 16:56 GMT+08:00 Balicanta notifications@github.com:

**Comment by dinos80152** [comment]
真的有醜，應該有像namespace還是package的東西吧?
